const container = document.querySelector(".list");
const movies = [
  {name: "Felicità",    url: "felicita/h/14283213_40099",    year: "2020", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Yakari, la grande aventure",   url: "yakari-la-grande-aventure/h/14460003_40099",    year: "2020", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "La vie très privée de monsieur Sim",   url: "la-vie-tres-privee-de-monsieur-sim/h/6031610_40099",    year: "2015", genre:"Comédie Dramatique", keyword:"",stars:"star-three"  },
  {name: "Les acteurs",   url: "les-acteurs/h/310360_40099",    year: "2000", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Terra Willy, planète inconnue",   url: "terra-willy-planete-inconnue/h/11364255_40099",    year: "2019", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "La grande aventure Lego",  url: "la-grande-aventure-lego/h/3753674_40099",    year: "2014", genre:"Animation", keyword:"",stars:"star-four"  },
  {name: "I Love You Phillip Morris",  url: "i-love-you-phillip-morris/h/276693_40099",    year: "2009", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Barton Fink",  url: "barton-fink/h/1727329_40099",    year: "1991", genre:"Comédie Dramatique", keyword:"",stars:"star-four"  },
  {name: "Hellboy",  url: "hellboy/h/460023_40099",    year: "2004", genre:"Fantastique", keyword:"",stars:"star-three"  },
  {name: "Astérix et le coup du menhir",  url: "asterix-et-le-coup-du-menhir/h/267699_40099",    year: "1989", genre:"Jeunesse", keyword:"",stars:"star-three"  },
  {name: "La folie des grandeurs",    url: "la-folie-des-grandeurs/h/437616_40099",    year: "1971", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Kill Bill Volume 1",  url: "kill-bill-volume-1/h/447165_40099",    year: "2003", genre:"Action", keyword:"",stars:"star-four"  },
  {name: "Le cinquième élément",  url: "le-cinquieme-element/h/2799080_40099",    year: "1997", genre:"Science-fiction", keyword:"",stars:"star-four"  },
  {name: "Pulp Fiction",   url: "pulp-fiction/h/113934_40099",    year: "1994", genre:"Suspense", keyword:"",stars:"star-four"  },
  {name: "DieHard: Une journée en enfer",    url: "une-journee-en-enfer/h/1784027_40099",    year: "1995", genre:"Action", keyword:"",stars:"star-four"  },
  {name: "DieHard: 58 minutes pour vivre",   url: "58-minutes-pour-vivre/h/771194_40099",    year: "1990", genre:"Action", keyword:"",stars:"star-three"  },
  {name: "DieHard: Piège de cristal",   url: "piege-de-cristal/h/771207_40099",    year: "1988", genre:"Action", keyword:"",stars:"star-four"  },
  {name: "Tout simplement noir",  url: "tout-simplement-noir/h/14250527_40099",    year: "2020", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Les Schtroumpfs 2", url: "les-schtroumpfs-2/h/4884171_40099",    year: "2013", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "Les rebelles de la forêt",  url: "les-rebelles-de-la-foret/h/442100_40099",    year: "2006", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "Monster House",  url: "monster-house/h/766310_40099",    year: "2006", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "Les pirates ! Bons à rien, mauvais en tout",  url: "les-pirates-bons-a-rien-mauvais-en-tout/h/490525_40099",    year: "2012", genre:"Animation", keyword:"Aaardman",stars:"star-three"  },
  {name: "Tartarin de Tarascon",  url: "tartarin-de-tarascon/h/6972241_40099",    year: "1934", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Ah ! Si j'étais riche",   url: "ah-si-j-etais-riche/h/114365_40099",    year: "2002", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Le dîner de cons",   url: "le-diner-de-cons/h/1445242_40099",    year: "1997", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Mais où est donc passée la 7e compagnie ?", url: "mais-ou-est-donc-passee-la-7-e-compagnie/h/625644_40099",    year: "1973", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Quelques messieurs trop tranquilles",  url: "quelques-messieurs-trop-tranquilles/h/1064200_40099",    year: "1973", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Jour de fête",   url: "jour-de-fete/h/2767115_40099",    year: "1949", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Tout le monde il est beau, tout le monde il est gentil", url: "tout-le-monde-il-est-beau-tout-le-monde-il-est-gentil/h/180163_40099",    year: "1972", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Quai des Orfèvres",   url: "quai-des-orfevres/h/117558_40099",    year: "1947", genre:"Policier", keyword:"",stars:"star-four"  },
  {name: "Hôtel du Nord", url: "hotel-du-nord/h/3281152_40099",    year: "1938", genre:"Drame", keyword:"",stars:"star-four"  },
  {name: "Le distrait", url: "le-distrait/h/421862_40099",    year: "1970", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Marie Antoinette",  url: "marie-antoinette/h/437547_40099",    year: "2006", genre:"Histoire", keyword:"",stars:"star-three"  },
  {name: "L'impasse",   url: "l-impasse/h/612062_40099",    year: "1993", genre:"Suspense", keyword:"",stars:"star-four"  },
  {name: "Chappie",  url: "chappie/h/4814980_40099",    year: "2015", genre:"Science-fiction", keyword:"",stars:"star-three"  },
  {name: "Le jouet", url: "le-jouet/h/647019_40099",    year: "1976", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Passengers", url: "passengers/h/7908222_40099",    year: "2016", genre:"Science-fiction", keyword:"",stars:"star-three"  },
  {name: "Hop",  url: "hop/h/113811_40099",    year: "2011", genre:"Jeunesse", keyword:"",stars:"star-three"  },
  {name: "Le plus beau métier du monde",  url: "le-plus-beau-metier-du-monde/h/387689_40099",    year: "1996", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Batman",   url: "batman/h/12590458_40099",    year: "1989", genre:"Fantastique", keyword:"",stars:"star-three"  },
  {name: "Pierre Lapin", url: "pierre-lapin/h/9742193_40099",    year: "2018", genre:"Jeunesse", keyword:"",stars:"star-three"  },
  {name: "La traversée de Paris",  url: "la-traversee-de-paris/h/106904_40099",    year: "1956", genre:"Comédie dramatique", keyword:"",stars:"star-four"  },
  {name: "Le coup du parapluie",   url: "le-coup-du-parapluie/h/177993_40099",    year: "1989", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Les choristes",   url: "les-choristes/h/3080957_40099",    year: "2004", genre:"Comédie dramatique", keyword:"",stars:"star-four"  },
  {name: "Les bronzés font du ski",  url: "les-bronzes-font-du-ski/h/4661500_40099",    year: "1979", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Les Schtroumpfs et le village perdu",   url: "les-schtroumpfs-et-le-village-perdu/h/8420498_40099",    year: "2017", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "Paddington 2",   url: "paddington-2/h/9319792_40099",    year: "2017", genre:"Jeunesse", keyword:"",stars:"star-four"  },
  {name: "12 Years a Slave",   url: "12-years-a-slave/h/3615890_40099",    year: "2013", genre:"Drame", keyword:"",stars:"star-four"  },
  {name: "Bienvenue à Gattaca",  url: "bienvenue-a-gattaca/h/437345_40099",    year: "1997", genre:"Science-fiction", keyword:"",stars:"star-four"  },
  {name: "Master and Commander : de l'autre côté du monde",  url: "master-and-commander-de-l-autre-cote-du-monde/h/1893709_40099",    year: "2003", genre:"Aventure", keyword:"",stars:"star-four"  },
  {name: "Hulk",  url: "hulk/h/1101970_40099",    year: "2003", genre:"Action", keyword:"",stars:"star-three"  },
  {name: "Chinatown",  url: "chinatown/h/200345_40099",    year: "1974", genre:"Suspense", keyword:"",stars:"star-four"  },
  {name: "Moi, moche et méchant",  url: "moi-moche-et-mechant/h/733525_40099",    year: "2010", genre:"Animation", keyword:"",stars:"star-four"  },
  {name: "Jumanji",  url: "jumanji/h/667007_40099",    year: "1995", genre:"Fantastique", keyword:"",stars:"star-four"  },
  {name: "Retour vers le futur 3",  url: "retour-vers-le-futur-3/h/1063987_40099",    year: "1990", genre:"Science-fiction", keyword:"",stars:"star-four"  },
  {name: "Retour vers le futur 2",  url: "retour-vers-le-futur-2/h/1063986_40099",    year: "1989", genre:"Science-fiction", keyword:"",stars:"star-four"  },
  {name: "Retour vers le futur",  url: "retour-vers-le-futur/h/1063985_40099 ",    year: "1985", genre:"Science-fiction", keyword:"",stars:"star-four"  },
  {name: "Les minions",  url: "les-minions/h/5281800_40099",    year: "2015", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "L'armée des ombres",  url: "l-armee-des-ombres/h/437688_40099",    year: "1969", genre:"Drame", keyword:"",stars:"star-four"  },
  {name: "Playtime",  url: "playtime/h/2863218_40099",    year: "1967", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Les vacances de Mr Hulot",  url: "les-vacances-de-monsieur-hulot/h/2799017_40099",    year: "1953", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Mon oncle",  url: "mon-oncle/h/2830409_40099",    year: "1958", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Taxi",  url: "taxi/h/267817_40099",    year: "1997", genre:"Action", keyword:"",stars:"star-three"  },
  {name: "Les barbouzes",  url: "les-barbouzes/h/267781_40099",    year: "1964", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Les tontons flingueurs",  url: "les-tontons-flingueurs/h/438484_40099",    year: "1963", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Un chien dans un jeu de quilles",  url: "un-chien-dans-un-jeu-de-quilles/h/516885_40099",    year: "1983", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "A gauche en sortant de l'ascenceur", url: "a-gauche-en-sortant-de-l-ascenseur/h/413625_40099",    year: "1988", genre:"Comédie", keyword:"",stars:"star-three"  },
  {name: "Premier contact", url: "premier-contact/h/7798919_40099",    year: "2016", genre:"Science-fiction", keyword:"",stars:"star-four"  },
  {name: "Les animaux fantastiques", url: "les-animaux-fantastiques/h/7681782_40099",    year: "2016", genre:"Fantastique", keyword:"",stars:"star-three"  },
  {name: "Deadpool", url: "deadpool/h/6303697_40099",    year: "2016", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Astérix: Le domaine des dieux", url: "asterix-le-domaine-des-dieux/h/4891937_40099",    year: "2014", genre:"Animation", keyword:"",stars:"star-three"  },
  {name: "Les fils de l'homme", url: "les-fils-de-l-homme/h/113969_40099",    year: "", genre:"Science-fiction", keyword:"",stars:"star-four"  },
  {name: "Kong: Skull island", url: "kong-skull-island/h/8297216_40099",    year: "2017", genre:"Aventure", keyword:"",stars:"star-three"  },
  {name: "Les aventures de Rabbit Jacob", url: "les-aventures-de-rabbi-jacob/h/1060462_40099",    year: "1973", genre:"Comédie", keyword:"",stars:"star-four"  },
  {name: "Océans", url: "oceans/h/174956_40099",    year: "2009", genre:"Documentaire", keyword:"",stars:"star-four"  },
  {name: "Le peuple migrateur", url: "le-peuple-migrateur/h/459649_40099",    year: "2001", genre:"Documentaire", keyword:"",stars:"star-four"  },
  {name: "Chimpanzés : Les artisans du Bossou", url: "chimpanzes-les-artisans-du-bossou/h/1994860_40099",    year: "2001", genre:"Documentaire", keyword:"",stars:"star-three"  },
  {name: "Nikita", url: "nikita/h/96172_40099",    year: "1990", genre:"Suspense", keyword:"",stars:"star-four"  },
  {name: "Le grand bleu", url: "le-grand-bleu-version-longue/h/15199135_40099",    year: "1988", genre:"Aventure", keyword:"",stars:"star-four"  },
  {name: "Léon", url: "leon/h/437617_40099",    year: "1994", genre:"Suspense", keyword:"",stars:"star-four"  },
  {name: "Hook ou la revanche du capitaine Crochet", url: "hook-ou-la-revanche-du-capitaine-crochet/h/1060663_40099",    year: "1991", genre:"Fantastique", keyword:"", stars:"star-three" },
  {name: "Etre et avoir", url: "etre-et-avoir/h/437915_40099",    year: "2002", genre:"Documentaire", keyword:"", stars:"star-four" },
  {name: "Kirikou et la sorcière", url: "kirikou-et-la-sorciere/h/569183_40099",    year: "1998", genre:"Animation", keyword:"", stars:"star-four" },
  {name: "Joker", url: "joker/h/12513133_40099",    year: "2019", genre:"Suspense", keyword:"", stars:"star-four" },
  {name: "La mule", url: "la-mule/h/10939764_40099",    year: "2018", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Le grand bain", url: "le-grand-bain/h/10445994_40099",    year: "2018", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Ready Player One", url: "ready-player-one/h/9716666_40099",    year: "2018", genre:"Science-fiction", keyword:"", stars:"star-four" },
  {name: "Une affaire de famille", url: "une-affaire-de-famille/h/10719337_40099",    year: "2018", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Pentagon Papers", url: "pentagon-papers/h/9488776_40099",    year: "2017", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "La ch'tite famille", url: "la-ch-tite-famille/h/9620337_40099",    year: "2018", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Blade Runner 2049", url: "blade-runner-2049/h/9078527_40099",    year: "2017", genre:"Science-fiction", keyword:"", stars:"star-four" },
  {name: "007 Spectre", url: "007-spectre/h/5851241_40099",    year: "2015", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Dallas Buyers Club", url: "dallas-buyers-club/h/3716357_40099",    year: "2013", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Paddington", url: "paddington/h/4940838_40099",    year: "2014", genre:"Jeunesse", keyword:"", stars:"star-four" },
  {name: "Les gardiens de la galaxie", url: "les-gardiens-de-la-galaxie/h/4452285_40099",    year: "2014", genre:"Science-fiction", keyword:"", stars:"star-four" },
  {name: "Gone Girl", url: "gone-girl/h/4720696_40099",    year: "2014", genre:"Suspense", keyword:"", stars:"star-four" },
  {name: "Django Unchained", url: "django-unchained/h/1820212_40099",    year: "2012", genre:"Western", keyword:"", stars:"star-four" },
  {name: "Prisoners", url: "prisoners/h/3126176_40099",    year: "2013", genre:"Suspense", keyword:"", stars:"star-four" },
  {name: "Le Hobbit : la désolation de Smaug", url: "le-hobbit-la-desolation-de-smaug/h/3464227_40099",    year: "2013", genre:"Fantastique", keyword:"", stars:"star-four" },
  {name: "Le Hobbit : un voyage inattendu", url: "le-hobbit-un-voyage-inattendu/h/1710478_40099",    year: "2012", genre:"Fantastique", keyword:"", stars:"star-four" },
  {name: "Skyfall", url: "skyfall/h/2746717_40099",    year: "2012", genre:"Action", keyword:"", stars:"star-four" },
  {name: "Moonrise Kingdom", url: "moonrise-kingdom/h/667109_40099",    year: "2012", genre:"Comédie", keyword:"", stars:"star-four" },
  {name: "True Grit", url: "true-grit/h/118252_40099",    year: "2010", genre:"Western", keyword:"", stars:"star-four" },
  {name: "Intouchables", url: "intouchables/h/151459_40099",    year: "2011", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Les petits mouchoirs", url: "les-petits-mouchoirs/h/805882_40099",    year: "2010", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Shutter island", url: "shutter-island/h/276747_40099",    year: "2010", genre:"Suspense", keyword:"", stars:"star-three" },
  {name: "Papy fait de la résistance", url: "papy-fait-de-la-resistance/h/3311841_40099",    year: "1983", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Les saisons", url: "les-saisons/h/6231028_40099",    year: "2015", genre:"Documentaire", keyword:"", stars:"star-four" },
  {name: "Terre des Ours", url: "terre-des-ours/h/6045042_40099",    year: "2014", genre:"Documentaire", keyword:"", stars:"star-three" },
  {name: "Microcosmos", url: "microcosmos-le-peuple-de-l-herbe/h/433830_40099",    year: "1996", genre:"Documentaire", keyword:"", stars:"star-four" },
  {name: "Brendan et le secret de Kells", url: "brendan-et-le-secret-de-kells/h/446992_40099",    year: "2009", genre:"Animation", keyword:"", stars:"star-four" },
  {name: "Le chant de la mer", url: "le-chant-de-la-mer/h/5108908_40099",    year: "2014", genre:"Animation", keyword:"", stars:"star-four" },
  {name: "Cars", url: "cars-quatre-roues/h/603415_40099",    year: "2006", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Mickey, la magie de Noël", url: "mickey-la-magie-de-noel/h/928081_40099",    year: "2001", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Les indestructibles", url: "les-indestructibles/h/205541_40099",    year: "2004", genre:"Animation", keyword:"", stars:"star-four" },
  {name: "Baby Boss", url: "baby-boss/h/8390252_40099",    year: "2017", genre:"Animation", keyword:"", stars:"star-two" },
  {name: "Bee Movie", url: "bee-movie-drole-d-abeille/h/115385_40099",    year: "2007", genre:"Animation", keyword:"", stars:"star-two" },
  {name: "Madagascar", url: "madagascar/h/2919648_40099",    year: "2005", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Poltergeist", url: "poltergeist/h/5225552_40099",    year: "2015", genre:"Fantastique", keyword:"", stars:"star-four" },
  {name: "Pride", url: "pride/h/4634326_40099",    year: "2014", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Hours", url: "hours/h/4085430_40099",    year: "2013", genre:"Suspense", keyword:"", stars:"star-two" },
  {name: "Monument Men", url: "monuments-men/h/3864104_40099",    year: "2013", genre:"Guerre", keyword:"", stars:"star-three" },
  {name: "The Grand Budapest Hotel", url: "the-grand-budapest-hotel/h/4053009_40099",  year: "2014", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Philomena", url: "philomena/h/3568774_40099",    year: "2013", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Les rois mages", url: "les-rois-mages/h/650676_40099",    year: "2001", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Zulu", url: "zulu/h/3434946_40099",    year: "2013", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Quai d'Orsay", url: "quai-d-orsay/h/3221383_40099",    year: "2013", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "La vallée des loups", url: "la-vallee-des-loups/h/7948131_40099",    year: "2016", genre:"Documentaire", keyword:"", stars:"star-three" },
  {name: "La vie rêvée de Walter Mitty", url: "la-vie-revee-de-walter-mitty/h/3669184_40099",    year: "2013", genre:"Aventure", keyword:"", stars:"star-four" },
  {name: "Alceste à bicyclette", url: "alceste-a-bicyclette/h/1820209_40099",    year: "2012", genre:"Comédie dramatique", keyword:"", stars:"star-three" },
  {name: "L'odyssée de Pi", url: "l-odyssee-de-pi/h/1635398_40099",    year: "2012", genre:"Aventure", keyword:"", stars:"star-four" },
  {name: "Voisins du troisième type", url: "voisins-du-troisieme-type/h/1210319_40099",    year: "2012", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "The Descendants", url: "the-descendants/h/151408_40099",    year: "2011", genre:"Comédie dramatique", keyword:"", stars:"star-three" },
  {name: "La piel que habito", url: "la-piel-que-habito/h/436037_40099",    year: "2011", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "La fille du puisatier", url: "la-fille-du-puisatier/h/911527_40099",    year: "2011", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "L'age de glace 4", url: "l-age-de-glace-4-la-derive-des-continents/h/981890_40099",    year: "2012", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Titeuf, le film", url: "titeuf-le-film/h/113632_40099",    year: "2011", genre:"Animation", keyword:"", stars:"star-two" },
  {name: "127 heures", url: "127-heures/h/911521_40099",    year: "2010", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Wall Street : l'argent ne dort jamais", url: "wall-street-l-argent-ne-dort-jamais/h/242194_40099",    year: "2010", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Slumdog Millionaire", url: "slumdog-millionaire/h/911525_40099",    year: "2008", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Le jour d'après", url: "le-jour-d-apres/h/1198620_40099",    year: "2004", genre:"Action", keyword:"", stars:"star-two" },
  {name: "Braveheart", url: "braveheart/h/573582_40099",    year: "1995", genre:"Aventure", keyword:"", stars:"star-four" },
  {name: "Les trois frères", url: "les-trois-freres/h/2919583_40099",    year: "1995", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Sunshine", url: "sunshine/h/438278_40099",    year: "2007", genre:"Science-fiction", keyword:"", stars:"star-three" },
  {name: "Phone Game", url: "phone-game/h/1401982_40099",    year: "2002", genre:"Suspense", keyword:"", stars:"star-three" },
  {name: "Madame Doubtfire", url: "madame-doubtfire/h/168665_40099",    year: "1993", genre:"Comédie", keyword:"", stars:"star-four" },
  {name: "Conan le barbare", url: "conan-le-barbare/h/2229368_40099",    year: "1982", genre:"Aventure", keyword:"", stars:"star-three" },
  {name: "Chicken run", url: "chicken-run/h/413605_40099",    year: "2000", genre:"Animation", keyword:"", stars:"star-four" },
  {name: "Brooklyn", url: "brooklyn/h/6464158_40099",    year: "2015", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Snoopy et les Peanuts", url: "snoopy-et-les-peanuts-le-film/h/6067032_40099",    year: "2015", genre:"Animation", keyword:"", stars:"star-two" },
  {name: "Les suffragettes", url: "les-suffragettes/h/5890850_40099",    year: "2015", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Alexandre", url: "alexandre/h/437101_40099",    year: "2004", genre:"Histoire", keyword:"", stars:"star-three" },
  {name: "La reine Margot", url: "la-reine-margot/h/1512012_40099",    year: "1993", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Les gamins", url: "les-gamins/h/2329165_40099",    year: "2013", genre:"Comédie", keyword:"", stars:"star-two" },
  {name: "Le cave se rebiffe", url: "le-cave-se-rebiffe/h/433204_40099",    year: "1961", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Vicky Cristina Barcelona", url: "vicky-cristina-barcelona/h/1784018_40099",    year: "2008", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Les goonies", url: "les-goonies/h/435659_40099",    year: "1985", genre:"Jeunesse", keyword:"", stars:"star-four" },
  {name: "Marie-Francine", url: "marie-francine/h/8643789_40099",    year: "2017", genre:"Comédie", keyword:"", stars:"star-two" },
  {name: "Le grand méchant Renard et autres contes", url: "le-grand-mechant-renard-et-autres-contes/h/8716590_40099",    year: "2017", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Problemos", url: "problemos/h/8569306_40099",    year: "2017", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Man of Steel", url: "man-of-steel/h/2669070_40099",    year: "2013", genre:"Fantastique", keyword:"", stars:"star-three" },
  {name: "American Sniper", url: "american-sniper/h/5268666_40099",    year: "2014", genre:"Guerre", keyword:"", stars:"star-three" },
  {name: "Interstellar", url: "interstellar/h/4920580_40099",    year: "2014", genre:"Science-fiction", keyword:"", stars:"star-four" },
  {name: "Le géant de fer", url: "le-geant-de-fer/h/240404_40099",    year: "1999", genre:"Animation", keyword:"", stars:"star-four" },
  {name: "100 000 dollars au soleil", url: "100-000-dollars-au-soleil/h/120667_40099",    year: "1964", genre:"Aventure", keyword:"", stars:"star-four" },
  {name: "L'arme fatale 3", url: "l-arme-fatale-3/h/1797802_40099",    year: "1992", genre:"Policier", keyword:"", stars:"star-four" },
  {name: "L'arme fatale 4", url: "l-arme-fatale-4/h/1797743_40099",    year: "1998", genre:"Policier", keyword:"", stars:"star-four" },
  {name: "L'arme fatale", url: "l-arme-fatale/h/1777460_40099",    year: "1987", genre:"Policier", keyword:"", stars:"star-four" },
  {name: "L'arme fatale 2", url: "l-arme-fatale-2/h/1797801_40099",    year: "1989", genre:"Policier", keyword:"", stars:"star-four" },
  {name: "Gravity", url: "gravity/h/3229004_40099",    year: "2013", genre:"Science-fiction", keyword:"", stars:"star-four" },
  {name: "Matrix", url: "matrix/h/114045_40099",    year: "1999", genre:"Science-fiction", keyword:"", stars:"star-four" },
  {name: "300", url: "300/h/438047_40099",    year: "2006", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Ocean's Eleven", url: "ocean-s-eleven/h/435044_40099",    year: "2001", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Godzilla", url: "godzilla/h/4107699_40099",    year: "2014", genre:"Science-fiction", keyword:"", stars:"star-three" },
  {name: "Inherent Vice", url: "inherent-vice/h/4815003_40099",    year: "2014", genre:"Policier", keyword:"", stars:"star-three" },
  {name: "Astérix: Les douze travaux d'Astérix", url: "les-douze-travaux-d-asterix/h/363817_40099",    year: "1976", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Astérix le Gaulois", url: "asterix-le-gaulois/h/302917_40099",    year: "1967", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Astérix chez les Bretons", url: "asterix-chez-les-bretons/h/235948_40099",    year: "1986", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "La cité de la peur", url: "la-cite-de-la-peur/h/437562_40099",    year: "1994", genre:"Comédie", keyword:"", stars:"star-four" },
  {name: "Astérix et Cléopâtre", url: "asterix-et-cleopatre/h/163731_40099",    year: "1968", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Sur la route de Madison", url: "sur-la-route-de-madison/h/435500_40099",    year: "1995", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Autant en emporte le vent", url: "autant-en-emporte-le-vent/h/200225_40099",    year: "1939", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Diversion", url: "diversion/h/4852272_40099",    year: "2015", genre:"Suspense", keyword:"", stars:"star-three" },
  {name: "San Andreas", url: "san-andreas/h/5145500_40099",    year: "2015", genre:"Action", keyword:"", stars:"star-two" },
  {name: "Le juge", url: "le-juge/h/4888831_40099",    year: "2014", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Harry Potter à l'école des sorciers", url: "harry-potter-a-l-ecole-des-sorciers/h/435039_40099",    year: "2001", genre:"Fantastique", keyword:"", stars:"star-four" },
  {name: "Voyage au centre de la terre 2", url: "voyage-au-centre-de-la-terre-2-l-ile-mysterieuse/h/436656_40099",    year: "2012", genre:"Aventure", keyword:"", stars:"star-two" },
  {name: "Pacific Rim", url: "pacific-rim/h/2787913_40099",    year: "", genre:"Science-fiction", keyword:"", stars:"star-three" },
  {name: "Gremlins 2", url: "u-s-marshals/h/725197_40099",    year: "2013", genre:"Fantastique", keyword:"", stars:"star-three" },
  {name: "Gremlins", url: "gremlins/h/800965_40099",    year: "1984", genre:"Fantastique", keyword:"", stars:"star-three" },
  {name: "Le nouveau stagiaire", url: "le-nouveau-stagiaire/h/5674590_40099",    year: "2015", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Strictly Criminal", url: "strictly-criminal/h/5929348_40099",    year: "2015", genre:"Suspense", keyword:"", stars:"star-three" },
  {name: "Les affranchis", url: "les-affranchis/h/436381_40099",    year: "1990", genre:"Suspense", keyword:"", stars:"star-four" },
  {name: "U.S. Marshals", url: "u-s-marshals/h/725197_40099",    year: "1998", genre:"Policier", keyword:"", stars:"star-three" },
  {name: "Happy Feet", url: "happy-feet/h/437810_40099",    year: "2006", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "L'associé du Diable", url: "l-associe-du-diable/h/200216_40099",    year: "1997", genre:"Fantastique", keyword:"", stars:"star-three" },
  {name: "Sherlock Holmes : jeu d'ombres", url: "sherlock-holmes-jeu-d-ombres/h/436368_40099",    year: "2011", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Sherlock Holmes", url: "sherlock-holmes/h/199769_40099",    year: "2009", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Blood Diamond", url: "blood-diamond/h/438089_40099",    year: "2006", genre:"Aventure", keyword:"", stars:"star-three" },
  {name: "Les sous-doués", url: "les-sous-doues/h/303001_40099",    year: "1980", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Le château de ma mère", url: "le-chateau-de-ma-mere/h/438490_40099",    year: "1990", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Les triplettes de Belleville", url: "les-triplettes-de-belleville/h/4247757_40099",    year: "2003", genre:"Animation", keyword:"", stars:"star-four" },
  {name: "La gloire de mon père", url: "la-gloire-de-mon-pere/h/438499_40099",    year: "1990", genre:"Comédie dramatique", keyword:"", stars:"star-four" },
  {name: "Le téléphone sonne toujours deux fois", url: "le-telephone-sonne-toujours-deux-fois/h/351196_40099",    year: "1984", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Le pôle express", url: "le-pole-express/h/1038437_40099",    year: "2004", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Charlie et la chocolaterie", url: "charlie-et-la-chocolaterie/h/437201_40099",    year: "2005", genre:"Jeunesse", keyword:"", stars:"star-four" },
  {name: "L'opération Corned Beef", url: "l-operation-corned-beef/h/1064009_40099",    year: "1990", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Le Caire confidentiel", url: "le-caire-confidentiel/h/8768703_40099",    year: "2017", genre:"Policier", keyword:"", stars:"star-three" },  
  {name: "Inception", url: "inception/h/510368_40099",    year: "2010", genre:"Science-fiction", keyword:"", stars:"star-three" },
  {name: "Invictus", url: "invictus/h/871468_40099",    year: "2009", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Midnight Special", url: "midnight-special/h/6503602_40099",    year: "2016", genre:"Science-fiction", keyword:"", stars:"star-three" },
  {name: "Agents très spéciaux : Code U.N.C.L.E.", url: "agents-tres-speciaux-code-u-n-c-l-e/h/5576427_40099",    year: "2015", genre:"Policier", keyword:"", stars:"star-three" },
  {name: "L'affaire Pélican", url: "l-affaire-pelican/h/812558_40099",    year: "1993", genre:"Suspense", keyword:"", stars:"star-three" },
  {name: "Au coeur de l'océan", url: "au-coeur-de-l-ocean/h/5997955_40099",    year: "2015", genre:"Aventure", keyword:"", stars:"star-two" },  
  {name: "Batman Begins", url: "batman-begins/h/437179_40099",    year: "2005", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Orange mécanique", url: "orange-mecanique/h/435045_40099",    year: "1971", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Gran Torino", url: "gran-torino/h/3441559_40099",    year: "2008", genre:"Suspense", keyword:"", stars:"star-four" },
  {name: "Je suis une légende", url: "je-suis-une-legende/h/185102_40099",    year: "2007", genre:"Science-fiction", keyword:"", stars:"star-three" },
  {name: "Impitoyable", url: "impitoyable/h/434653_40099",    year: "1992", genre:"Western", keyword:"", stars:"star-four" },
  {name: "Argo", url: "argo/h/1515972_40099",    year: "2012", genre:"Suspense", keyword:"", stars:"star-three" },  
  {name: "Blade Runner (Final Cut)", url: "blade-runner-final-cut/h/1099194_40099",    year: "1982", genre:"Science-fiction", keyword:"", stars:"star-four" },
  {name: "Citizen Kane", url: "citizen-kane/h/305809_40099",    year: "1941", genre:"Drame", keyword:"", stars:"star-four" },
  {name: "Conjuring 2", url: "conjuring-2-le-cas-enfield/h/7009425_40099",    year: "2016", genre:"Horreur", keyword:"", stars:"star-three" },
  {name: "Conjuring", url: "conjuring-les-dossiers-warren/h/2892135_40099",    year: "2013", genre:"Horreur", keyword:"", stars:"star-three" },  
  {name: "Kiss Kiss Bang Bang", url: "kiss-kiss-bang-bang/h/361058_40099",    year: "2005", genre:"Policier", keyword:"", stars:"star-three" },
  {name: "Les pleins pouvoirs", url: "les-pleins-pouvoirs/h/435548_40099",    year: "1997", genre:"Suspense", keyword:"", stars:"star-three" },
  {name: "Marseille", url: "marseille/h/6503644_40099",    year: "2016", genre:"Comédie dramatique", keyword:"", stars:"star-three" },
  {name: "Batman: The Dark Knight", url: "the-dark-knight-le-chevalier-noir/h/433162_40099",    year: "2008", genre:"Action", keyword:"", stars:"star-three" },  
  {name: "Batman: The Dark Knight Rises", url: "the-dark-knight-rises/h/1033296_40099",    year: "2012", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Le prestige", url: "le-prestige/h/2863354_40099",    year: "2006", genre:"Suspense", keyword:"", stars:"star-three" },
  {name: "Le monde de Nemo", url: "le-monde-de-nemo/h/116353_40099",    year: "2003", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "Zootopie", url: "zootopie/h/6344462_40099",    year: "2016", genre:"Animation", keyword:"Disney", stars:"star-four" },
  {name: "Very Bad Trip", url: "very-bad-trip/h/611911_40099",    year: "2009", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Edge of Tomorrow", url: "vivre-mourir-recommencer-edge-of-tomorrow/h/4217208_40099",    year: "2014", genre:"Science-fiction", keyword:"", stars:"star-three" },  
  {name: "Zodiac", url: "zodiac/h/942876_40099",    year: "2007", genre:"Suspense", keyword:"", stars:"star-two" },
  {name: "Mad Max : Fury Road", url: "mad-max-fury-road/h/5738491_40099",    year: "2015", genre:"Action", keyword:"", stars:"star-three" },
  {name: "Didier", url: "didier/h/911536_40099",    year: "1996", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Le Père Noël est une ordure", url: "le-pere-noel-est-une-ordure/h/4519507_40099",    year: "1982", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "#Chef", url: "chef/h/4833418_40099",    year: "2014", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "La tortue rouge", url: "la-tortue-rouge/h/7009426_40099",    year: "2016", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Paris pieds nus", url: "ouvert-la-nuit/h/7981356_40099",    year: "2016", genre:"Comédie", keyword:"", stars:"star-three" },
  {name: "Vice-Versa", url: "vice-versa/h/5196978_40099",    year: "2015", genre:"Animation", keyword:"Disney", stars:"star-four" },
  {name: "Un idiot à Paris", url: "un-idiot-a-paris/h/432921_40099",    year: "1967", genre:"Comédie", keyword:"", stars:"star-two" },
  {name: "Bodyguard", url: "bodyguard/h/107112_40099",    year: "1992", genre:"Policier", keyword:"", stars:"star-three" },
  {name: "Eyes Wide Shut", url: "eyes-wide-shut/h/199812_40099",    year: "1999", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "Spotlight", url: "spotlight/h/6231044_40099",    year: "2015", genre:"Drame", keyword:"", stars:"star-three" },
  {name: "The Shining", url: "shining/h/435556_40099",    year: "1980", genre:"Horreur", keyword:"", stars:"star-four" },
  {name: "Full Metal Jacket", url: "full-metal-jacket/h/435558_40099",    year: "1987", genre:"Guerre", keyword:"", stars:"star-four" },  
  {name: "L'illusionniste", url: "l-illusionniste/h/242145_40099",    year: "2010", genre:"Animation", keyword:"", stars:"star-three" },
  {name: "Ouvert la nuit", url: "ouvert-la-nuit/h/7981356_40099",    year: "2016", genre:"Comédie dramatique", keyword:"", stars:"star-two" },  
  {name: "Ernest et Célestine", url: "ernest-et-celestine/h/1617071_40099",    year: "2012", genre:"Animation", keyword:"", stars:"star-three" },  
  {name: "Somewhere", url: "somewhere/h/1144244_40099",    year: "2010", genre:"Comédie dramatique", keyword:"", stars:"star-three" },  
  {name: "Moi, Tonya", url: "moi-tonya/h/9595706_40099",    year: "2017", genre:"Drame", keyword:"", stars:"star-three" },  
  {name: "Lawrence d'Arabie", url: "lawrence-d-arabie/h/850551_40099",    year: "1962", genre:"Histoire", keyword:"", stars:"star-four" },  
  {name: "Le stratège", url: "le-stratege/h/776360_40099",    year: "2011", genre:"Drame", keyword:"", stars:"star-three" },  
  {name: "Godzilla", url: "godzilla/h/437531_40099",    year: "1998", genre:"Science-fiction", keyword:"", stars:"star-three" },  
  {name: "L'ours", url: "l-ours/h/433064_40099",    year: "1988", genre:"Aventure", keyword:"", stars:"star-four" },  
  {name: "Les ripoux", url: "les-ripoux/h/236010_40099",    year: "1984", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Drôle de drame", url: "drole-de-drame/h/375220_40099",    year: "1937", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Tchao pantin", url: "tchao-pantin/h/5525434_40099",    year: "1983", genre:"Drame", keyword:"", stars:"star-four" },  
  {name: "Se souvenir des belles choses", url: "se-souvenir-des-belles-choses/h/2235125_40099",    year: "2002", genre:"Drame", keyword:"", stars:"star-three" },  
  {name: "Un cœur en hiver", url: "un-coeur-en-hiver/h/438706_40099",    year: "1992", genre:"Drame", keyword:"", stars:"star-three" },  
  {name: "Nelly et monsieur Arnaud", url: "nelly-et-monsieur-arnaud/h/286005_40099",    year: "1995", genre:"Drame", keyword:"", stars:"star-three" },  
  {name: "Toy Story", url: "https://www.youtube.com/watch?v=CI5eQm-0CUw",    year: "1995", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "Toy Story 2", url: "https://www.youtube.com/watch?v=fBcb_eq9qOY",    year: "1999", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "Toy Story 3", url: "https://www.youtube.com/watch?v=1-8pawNzmXg",    year: "2010", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "Toy Story 4", url: "https://www.youtube.com/watch?v=Q-eU3fQmBaY",    year: "2010", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "The Green Mile", url: "https://www.youtube.com/watch?v=xZDY2pZneu0",    year: "1999", genre:"Drame", keyword:"", stars:"star-four" },  
  {name: "Kung Fu Panda", url: "https://www.youtube.com/watch?v=9oECG2PzobM",    year: "2008", genre:"Animation", keyword:"DreamWorks", stars:"star-four" },  
  {name: "Kung Fu Panda 2", url: "https://www.youtube.com/watch?v=6Pr-2XX7MUk",    year: "2011", genre:"Animation", keyword:"DreamWorks", stars:"star-three" },  
  {name: "Kung Fu Panda 3", url: "https://www.youtube.com/watch?v=H0f6RXtxGy4",    year: "2016", genre:"Animation", keyword:"DreamWorks", stars:"star-three" },  
  {name: "Happy Feet", url: "https://www.youtube.com/watch?v=i73C9dJUp3k",    year: "2006", genre:"Animation", keyword:"", stars:"star-three" },  
  {name: "Peanut Butter Falcon", url: "https://www.youtube.com/watch?v=BaWrDr9t65E",    year: "2019", genre:"Drame", keyword:"", stars:"star-four" },  
  {name: "Captain Fantastic", url: "https://www.youtube.com/watch?v=Bz4T31kc9Sw",    year: "2016", genre:"Aventure", keyword:"", stars:"star-four" },  
  {name: "Jurassic Park", url: "https://www.youtube.com/watch?v=7HnBs__n_cA",    year: "1993", genre:"Science-fiction", keyword:"", stars:"star-four" },  
  {name: "Jurassic Park 2", url: "https://www.youtube.com/watch?v=pz8d7ZHAc4w",    year: "1997", genre:"Science-fiction", keyword:"", stars:"star-three" },  
  {name: "Jurassic Park 3", url: "https://www.youtube.com/watch?v=GtmJuXPr4-I",    year: "2001", genre:"Science-fiction", keyword:"", stars:"star-three" },  
  {name: "Le fugitif", url: "https://www.youtube.com/watch?v=-OKQyIkUsXs",    year: "1993", genre:"Action", keyword:"", stars:"star-four" },  
  {name: "Le Film de Tigrou", url: "https://www.youtube.com/watch?v=xOYLc8KqVxw",    year: "2000", genre:"Animation", keyword:"Disney", stars:"star-three" },  
  {name: "La reine des neiges", url: "https://www.youtube.com/watch?v=Zh6OfduCP_E",    year: "2013", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "Jaws: Les dents de la mer", url: "https://www.youtube.com/watch?v=QSDqB7T8ItM",    year: "1975", genre:"Horreur", keyword:"", stars:"star-four" },  
  {name: "We need to talk about Kevin", url: "https://www.youtube.com/watch?v=x1RzSDSpBzo",    year: "2011", genre:"Thriller", keyword:"", stars:"star-four" },  
  {name: "Still Alice", url: "https://www.youtube.com/watch?v=oNyM0R1civc",    year: "2014", genre:"Drame", keyword:"", stars:"star-four" },  
  {name: "Melancholia", url: "https://www.youtube.com/watch?v=xqHAciEENaI",    year: "2011", genre:"Science-fiction", keyword:"", stars:"star-three" },  
  {name: "An American Tail", url: "https://www.youtube.com/watch?v=NT67Oz0u7lM",    year: "1986", genre:"Animation", keyword:"", stars:"star-three" },  
  {name: "Wallace & Gromit: The curse of the were-rabbit", url: "https://www.youtube.com/watch?v=gidNiWx0Ak0",    year: "2005", genre:"Animation", keyword:"Aardman", stars:"star-three" },  
  {name: "Hot Shots!", url: "https://www.youtube.com/watch?v=vlwByK3MguY",    year: "1991", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Up", url: "https://www.youtube.com/watch?v=wTpsA1myfPw",    year: "2009", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "The Lego Movie", url: "https://www.youtube.com/watch?v=lVl6UxiDQQs",    year: "2014", genre:"Animation", keyword:"", stars:"star-four" },  
  {name: "Jason Bourne", url: "https://www.youtube.com/watch?v=D-Ys_wNlaE4",    year: "2016", genre:"Action", keyword:"", stars:"star-three" },  
  {name: "Ice Age", url: "https://www.youtube.com/watch?v=AW9b6unX_wo",    year: "2002", genre:"Animation", keyword:"", stars:"star-three" },  
  {name: "Ghostbusters (2016)", url: "https://www.youtube.com/watch?v=RRxzVZWaGNA",    year: "2016", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Big Hero 6", url: "https://www.youtube.com/watch?v=-AWpph_Rvoo",    year: "2014", genre:"Animation", keyword:"Disney", stars:"star-four" },  
  {name: "Fun with Dick and Jane", url: "https://www.youtube.com/watch?v=V0OEC9rG6Jg",    year: "2005", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Bruce Almight", url: "https://www.youtube.com/watch?v=mbS0OK5Q8r4",    year: "2003", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Office Space", url: "https://www.youtube.com/watch?v=1hnKwTCcVSs",    year: "1999", genre:"Comédie", keyword:"", stars:"star-four" },  
  {name: "The thin red line", url: "https://www.youtube.com/watch?v=g1v9PwFrPYo",    year: "1998", genre:"Guerre", keyword:"", stars:"star-four" },  
  {name: "Idiocracy", url: "https://www.youtube.com/watch?v=Bb6j0SukuOE",    year: "2006", genre:"Comédie", keyword:"", stars:"star-three" },  
  {name: "Deux jours, une nuit", url: "https://www.youtube.com/watch?v=hiuAIzA9i98",    year: "2014", genre:"Drame", keyword:"", stars:"star-three" },  
  {name: "Groundhog Day", url: "https://www.youtube.com/watch?v=1VWbrFqTyCA",    year: "1993", genre:"Comédie", keyword:"", stars:"star-four" },  
  {name: "Eternal Sunshine of the Spotless Mind", url: "https://www.youtube.com/watch?v=-98VknWkSWo",    year: "2004", genre:"Science-fiction", keyword:"", stars:"star-four" },  
  {name: "Be Kind Rewind", url: "https://www.youtube.com/watch?v=MaDKdvArDkE",    year: "2008", genre:"Comédie", keyword:"", stars:"star-three" },  
   {name: "Fantastic Mr. Fox", url: "https://www.youtube.com/watch?v=7_tVZQIM37s",    year: "2009", genre:"Animation", keyword:"", stars:"star-four" },  
   {name: "Honey, I Shrunk the Kids", url: "https://www.youtube.com/watch?v=Zoivkxpf-Jc",    year: "1989", genre:"Jeunesse", keyword:"", stars:"star-three" },  
   {name: "Two Lovers", url: "https://www.youtube.com/watch?v=6pzXDL8UAWc",    year: "2008", genre:"Drame", keyword:"", stars:"star-three" },  
   {name: "Babel", url: "https://www.youtube.com/watch?v=8JQS_KkpJ4g",    year: "2006", genre:"Drame", keyword:"", stars:"star-three" },  
   {name: "The Goonies", url: "https://www.youtube.com/watch?v=WTcsNtu8Nh0",    year: "1985", genre:"Jeunesse", keyword:"", stars:"star-four" },  
   {name: "Dumb & Dumber", url: "https://www.youtube.com/watch?v=RiEYvpZef_s",    year: "1994", genre:"Comédie", keyword:"", stars:"star-three" },  
   {name: "The Wolf of Wall Street", url: "https://www.youtube.com/watch?v=Bbn43IhaiqQ",    year: "2013", genre:"Comédie", keyword:"", stars:"star-four" },  
   {name: "The Internship", url: "https://www.youtube.com/watch?v=_MitCrF6Xsc",    year: "2013", genre:"Comédie", keyword:"", stars:"star-three" },  
   {name: "Apollo 13", url: "https://www.youtube.com/watch?v=y98JSUVWj7I",    year: "1995", genre:"Drame", keyword:"", stars:"star-four" },  
   {name: "We own the night", url: "https://www.youtube.com/watch?v=bRIYrLoY_wQ",    year: "2007", genre:"Thriller", keyword:"", stars:"star-three" },  
   {name: "Rain Man", url: "https://www.youtube.com/watch?v=glK8NN4u3tw",    year: "1988", genre:"Drame", keyword:"", stars:"star-four" },  
   {name: "Alien", url: "https://www.youtube.com/watch?v=IMZpZiEsk4g",    year: "1979", genre:"Horreur", keyword:"", stars:"star-four" },  
   {name: "The Mask", url: "https://www.youtube.com/watch?v=ATO4bkj67ew",    year: "1994", genre:"Comédie", keyword:"", stars:"star-three" },  
   {name: "Escape from Alcatraz", url: "https://www.youtube.com/watch?v=Z1iEGJL5z6E",    year: "1979", genre:"Drame", keyword:"", stars:"star-four" },  
   {name: "Man on Fire", url: "https://www.youtube.com/watch?v=nfJOW7CCbEM",    year: "2004", genre:"Drame", keyword:"", stars:"star-four" },  
   {name: "Good Will Hunting", url: "https://www.youtube.com/watch?v=iZsVl69Xd_w",    year: "1997", genre:"Drame", keyword:"", stars:"star-four" },  
   {name: "Walk the line", url: "https://www.youtube.com/watch?v=j45l8Vb0Wok",    year: "2005", genre:"Drame", keyword:"", stars:"star-four" },  
   {name: "Master And Commander", url: "https://www.youtube.com/watch?v=6UCAju6j0Ak",    year: "2003", genre:"Drame", keyword:"", stars:"star-four" },  
   {name: "Into the Wild", url: "https://www.youtube.com/watch?v=QO3vYHdvx3s",    year: "2007", genre:"Aventure", keyword:"", stars:"star-four" },  
   {name: "Once upon a time in the West", url: "https://www.youtube.com/watch?v=euia5cbhYxo",    year: "1968", genre:"Western", keyword:"", stars:"star-four" },  
   {name: "Wall E", url: "https://www.youtube.com/watch?v=TbT3P_bsgcg",    year: "2008", genre:"Animation", keyword:"Disney", stars:"star-four" },  
   {name: "Ratatouille", url: "https://www.youtube.com/watch?v=BOzQaDg01ZY",    year: "2007", genre:"Animation", keyword:"Disney", stars:"star-four" },  




  ];
  
  
const rowWidth = 50 // how many images per row?
const showMovies = () => {
  const options = {
    valueNames: [ 'name', 'year', 'genre', 'keyword', 'stars'  ],
    item: ({ name, url, year, genre, keyword, stars, index }) => {
      const row = index === 0 ? 0 : Math.floor(index / rowWidth)
      const xPos = -111 * (index - row * rowWidth)
      const yPos = -167 * row
      return `<li class="fade-in" style="animation-delay: calc(1s * 0.005 * ${index} ); ">
        <a href="https://vod.canalplus.com/cinema/${url}" >
          <div class="pi"  style="background-position: ${xPos}px ${yPos}px;"></div>
          <h3 class="name">${name}</h3>
          <div class="star ${stars}"></div>
          <h4 class="genre">${genre}</h4>
          <h4 class="year">${year}</h4>
          
          </a>
      </li>`
    }
  };
const userList = new List('collection', options);
const movieCallback = (movie, index) => userList.add({ ...movie, index })
movies.forEach(movieCallback);


var filterJeunesse = document.getElementById("filter-jeunesse");
var filterComedie = document.getElementById("filter-comedie");
var filterAction = document.getElementById("filter-action");
var filterDisney = document.getElementById("filter-disney");
var filterDocumentaire = document.getElementById("filter-documentaire");
var removeFiltersButton = document.getElementById("removeFilters");



filterJeunesse.addEventListener("click", function() {userList.filter(function(item) {if (item.values().genre == "Animation") {return true;} else {return false;}});});
filterComedie.addEventListener("click", function() {userList.filter(function(item) {if (item.values().genre == "Comédie") {return true;} else {return false;}});});
filterAction.addEventListener("click", function() {userList.filter(function(item) {if (item.values().genre == "Action") {return true;} else {return false;}});});
filterDisney.addEventListener("click", function() {userList.filter(function(item) {if (item.values().keyword == "Disney") {return true;} else {return false;}});});
filterDocumentaire.addEventListener("click", function() {userList.filter(function(item) {if (item.values().genre == "Documentaire") {return true;} else {return false;}});});


removeFiltersButton.addEventListener("click", function() {userList.filter();});

};



  document.addEventListener("DOMContentLoaded", showMovies);


  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function() {
      navigator.serviceWorker
        .register("/m1/serviceWorker.js")
        .then(res => console.log("service worker registered"))
        .catch(err => console.log("service worker not registered", err));
    });
  }